[12:56 am, 13/07/2023] Rajashekhar Reddy CT: apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo 
  namespace: venky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
        - name: dotnetdemo
          image: kubedkr.azurecr.io/dotnet-web:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: macbook
[12:56 am, 13/07/2023] Rajashekhar Reddy CT: apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: venky
spec:
  selector:
    app: dotnetdemo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
